<a href="https://colab.research.google.com/github/Mariusz-Bienasz/Python_project_7/blob/main/Lab7c_Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programowanie w Python
Autor dr Aneta Polewko-Klim

## NumPy  
Homepage - http://www.numpy.org/  
QuickStart - https://docs.scipy.org/doc/numpy-dev/user/quickstart.html  
GitHub - https://github.com/numpy/numpy
**Additional tutorials**  
For machine learning programmers: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html
Numerical Computing in Python - http://nbviewer.jupyter.org/github/phelps-sg/python-bigdata/blob/master/src/main/ipynb/numerical-slides.ipynb

**NumPy** is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities  

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.  
See more information: http://www.numpy.org/

## import

In [1]:
 import numpy as np  # importowanie zawartości biblioteki, zmiana nazwy bibliteki na skrót do nazwy

## tworzenie tablicy array  

In [2]:
a = np.array([[0, 1],[2,3], [4,5]])   # funkcja array,
a
# struktura logiczna funkcji:   nazwaZmiennej = nazwaFunkcji(argumenty wejściowe funkcji),
#  nazwaZmiennej, zawiera argument lub argumenty wyściowe funkcji

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
# elementy tablicy mogą zawierać różne typy proste danych

In [4]:
m = np.array([['ala', 10],[2.45678,20], [True,50]])
m

array([['ala', '10'],
       ['2.45678', '20'],
       ['True', '50']], dtype='<U32')

In [5]:
a*10

array([[ 0, 10],
       [20, 30],
       [40, 50]])

In [6]:
[[0, 1],[2,3],[4,5]] * 10

[[0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5],
 [0, 1],
 [2, 3],
 [4, 5]]

In [7]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [8]:
1*10

10

In [9]:
type([1])

list

In [10]:
b = np.array([[20,30], [10,20], [0,10]])
b

array([[20, 30],
       [10, 20],
       [ 0, 10]])

In [11]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
c = b*a
c

array([[ 0, 30],
       [20, 60],
       [ 0, 50]])

In [13]:
c.T

array([[ 0, 20,  0],
       [30, 60, 50]])

## array: zeros, ones, random  

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((2, 3, 2))  # tablica 3D lub więcej  zeros(N-wymiar,liczba wierszy,liczba kolumn)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [20]:
np.random.rand(3)

array([0.40575623, 0.01426422, 0.20256105])

In [21]:
np.random.rand(3,2)

array([[0.85108285, 0.69360736],
       [0.733669  , 0.77483586],
       [0.9864351 , 0.36896399]])

## arange and reshape

https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

In [22]:
np.arange(5)   # numeracja/indeksowanie w python jest od zera, np. 1 element wektora ma indeks 0

array([0, 1, 2, 3, 4])

In [23]:
np.array(range(5))  # range(N)   -> tworzy wektor liczb 0,1,2,3,4,...,N-1  wykorzystywany np. w pętli for

array([0, 1, 2, 3, 4])

In [24]:
np.arange(1,5)  # arange(min,max)   tu  zakres: min = 1 do max = 5

array([1, 2, 3, 4])

In [25]:
np.arange(0, 100, 25)  # arange(min,max,krok)   tu  zakres: min = 0 do max = 100, krok=25

array([ 0, 25, 50, 75])

In [26]:
np.arange(0, 5, .25)  # zapis równoważny: 0.25 <=> .25

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

In [27]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
a.reshape(6)  # elementy tablicy ustaw jako wektor

array([0, 1, 2, 3, 4, 5])

In [29]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
np.arange(20).reshape(4, 5)  # kolejne funkcje są wywoływane jedna po drugiej (oszczędzamy linijki kodu, lepsza czytelność)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
np.arange(5).reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5).reshape(-1,1)  # odpowiednik transpozycji dla tablic 1D

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [34]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
a.T  # transpozycja

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## ndarray  
Informacje o macierzach N-wymiarowych:
https://docs.scipy.org/doc/numpy-1.11.0/reference/arrays.ndarray.html

### shape

In [36]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
a.shape  # rozmiar tablicy

(4, 5)

In [38]:
d = np.ones((3,5,2))
d

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [39]:
d.shape

(3, 5, 2)

In [40]:
print(np.arange(60).reshape(4,15)) # kolejne po sobie 60-elementów wstaw kolejno w 4 wiersze, 15 kolumn

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]


Python **len** function returns size of first dimension

In [41]:
a.shape # shape wskazuje na wymiar (liczba wierszy,liczba kolumn)
# nawiasy () ma krotka,  # nawiasy [] ma lista
# zawartości krotki nie można zmieniać, listy tak

(4, 5)

In [42]:
a.shape[1] # liczba kolumn, podaj wartość drugiego elementu z krotki  niech  k=(3,8) wówczas k[0] to 3, k[1] to 8

5

In [43]:
a.shape[0]   # liczba wierszy

4

In [44]:
len(a)

4

### ndim

In [45]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
a.ndim  # wymiar macierzy

2

In [47]:
dim1D = np.random.rand((2))
print(dim1D)
print(dim1D.ndim)

[0.42745842 0.09679791]
1


In [48]:
dim2D = np.zeros((2,2))
print(dim2D)
print(dim2D.ndim)

[[0. 0.]
 [0. 0.]]
2


In [49]:
dim3D = np.ones((2,2,2))
print(dim3D)
print(dim3D.ndim)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
3


### size

In [50]:
dim2D.size  # łączna ilość elementów w tablicy

4

In [51]:
np.ones((3, 4, 2)).size

24

### dtype & astype

W python dostępne są różne typy proste zmiennych np.:
<table>
<tr><th>type</th><th>opis</th></tr>
<tr><td>**bool**</td><td>logiczny (True or False)</td></tr>
<tr><td>**int**</td><td>liczba całkowita</td></tr>
<tr><td>**float**</td><td>liczba zmiennoprzecinkowych</td></tr>
<tr><td>**complex**</td><td>liczba urojona</td></tr>
</table>

In [52]:
arrayB = np.array([1, 2, 3])
arrayB.dtype   # podaj typ

dtype('int64')

In [53]:
arrayC = np.array([True, False])
arrayC.dtype

dtype('bool')

In [54]:
arrayD = np.array([1,2,3], dtype='float')  # można określić/narzucić na wejściu typ
arrayD.dtype

dtype('float64')

In [55]:
arrayE = np.array([1,0,1,0], dtype=np.bool)
arrayE.dtype

dtype('bool')

In [56]:
arrayF32 = np.array([10, 10000])
print(arrayF32)
print(arrayF32.dtype)
arrayF8 = arrayF32.astype(np.int8)
print(arrayF8.dtype)

[   10 10000]
int64
int8


### itemsize

In [57]:
dim1D.dtype

dtype('float64')

In [58]:
dim1D.itemsize # podanie rozmiaru w bajtach każdego elementu tablicy

8

In [59]:
np.set_printoptions(threshold=1000)

# operacje podstawowe na tablicach, basic operations

In [60]:
a = np.array([20,30,40,50])
print(a)
b = np.arange(4)
print(b)

[20 30 40 50]
[0 1 2 3]


In [61]:
c = a - b
c

array([20, 29, 38, 47])

In [62]:
b**2  # potęgowanie

array([0, 1, 4, 9])

In [63]:
a < 50  # które elementy macierzy a są mniejsze od 50

array([ True,  True,  True, False])

In [64]:
a <= 30  # które elementy macierzy a są mniejsze lub równe od 50

array([ True,  True, False, False])

In [65]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])

In [66]:
A*B  # mnożenie tablicowe, element razy element

array([[2, 0],
       [0, 4]])

In [67]:
A.dot(B) # mnożenie macierzowe zwróć uwagę że tu mamy nazwę metody a nie funkcji
# struktura logiczna      nazwaObiektu.nazwaMetody

array([[5, 4],
       [3, 4]])

In [68]:
np.dot(A, B) # mnożenie macierzowe  jako funkcja

array([[5, 4],
       [3, 4]])

In [69]:
A.sum()  # suma

np.int64(3)

In [70]:
A.mean() # średnia

np.float64(0.75)

In [71]:
A.min()  # element o minimalnej wartości
A.max()  # element o maxmalnej wartości

np.int64(1)

# operacje dla tablic różnych typów

In [72]:
a = np.random.rand(3)
print("a type:", a.dtype)
b = np.ones(3, dtype=np.int32)
print("b type:", b.dtype)
c = a+b
print("c type:", c.dtype)

a type: float64
b type: int32
c type: float64


## operacje dla tablic o wymarach > 2D

In [73]:
arrayG = np.arange(12).reshape(2, 6)
print(arrayG)
print(arrayG.sum(axis = 0)) # suma każdego wiersza
print('sum of each row')
print(arrayG.sum(axis = 1)) # suma każdej kolumny
print(arrayG.cumsum(axis=1)) # sumowanie skumulowane każdej kolumny
print(np.array([1,2]) + np.array([[1,2], [1,2]]))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 6  8 10 12 14 16]
sum of each row
[15 51]
[[ 0  1  3  6 10 15]
 [ 6 13 21 30 40 51]]
[[2 4]
 [2 4]]


## przykłady funkcji matematycznych

In [74]:
arrayH = np.arange(6)

In [75]:
np.exp(arrayH)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [76]:
np.sqrt(arrayH)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [77]:
np.cos(arrayH)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [78]:
x = np.linspace(0, np.pi, 5)  # 5-elementowy wektor w zakresie od 0 do pi, użyteczny do rysowania wykresów
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

# indexing, slicing and iterating

In [79]:
arrayI = np.arange(10)**5
print(arrayI)
print(arrayI[3])
print(arrayI[2:5])

[    0     1    32   243  1024  3125  7776 16807 32768 59049]
243
[  32  243 1024]


In [80]:
for row in arrayI:
     print(row)

0
1
32
243
1024
3125
7776
16807
32768
59049


In [81]:
for element in arrayI.flat:
    print(element)

0
1
32
243
1024
3125
7776
16807
32768
59049


In [82]:
arrayI.ravel()

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

Similar efect to  
```python
for element in b.flat```

In [83]:
for element in arrayI.ravel():
    print(element)

0
1
32
243
1024
3125
7776
16807
32768
59049


# składanie tablic

In [84]:
a = np.floor(10*np.random.random((3,3))) # floor, zaokrąglanie liczb do dołu, round, w górę
print(a)
print('#################')
b = np.round(10*np.random.random((3,3)))
print(b)

[[7. 4. 2.]
 [5. 6. 8.]
 [2. 2. 2.]]
#################
[[7. 3. 8.]
 [5. 9. 1.]
 [2. 8. 1.]]


In [85]:
np.vstack([a,b]) # wierszami

array([[7., 4., 2.],
       [5., 6., 8.],
       [2., 2., 2.],
       [7., 3., 8.],
       [5., 9., 1.],
       [2., 8., 1.]])

In [86]:
np.hstack([a,b]) # kolumnami

array([[7., 4., 2., 7., 3., 8.],
       [5., 6., 8., 5., 9., 1.],
       [2., 2., 2., 2., 8., 1.]])

# tworzenie macierzy

In [87]:
a = np.array([[1,2], [3, 'ala']])
b = np.matrix([[1,2], [3,'ala']])

In [88]:
a

array([['1', '2'],
       ['3', 'ala']], dtype='<U21')

In [89]:
b

matrix([['1', '2'],
        ['3', 'ala']], dtype='<U21')

In [90]:
a[1] # 2-gi wiersz

array(['3', 'ala'], dtype='<U21')

In [91]:
a[1,1] # a[wiersz,kolumna]

np.str_('ala')

In [93]:
a+b

matrix([['11', '22'],
        ['33', 'alaala']], dtype='<U42')

In [95]:
a*b

ValueError: data type must provide an itemsize